id: I9E657673
legacy_id: P000472
ocr_import_info:
  bdrc_scan_id: W1KG11691
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T23:04:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:01:02.004047+00:00'
last_modified: 2022-08-31 11:01:10.104837
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11691
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11691
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེས་རབ་བློ་ལྡན་གྱི་རྣམ་ཐར་དང་མགུར་འབུམ།
  author: ཤེས་རབ་བློ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.8306056758422392
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG11693:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11693
      total_pages: 262
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11693.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.8306056758422392
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
